force/objects/Prime__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <label>Ordinal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Prime</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Prime Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/main/default/classes/PrimeSelector.cls
public class PrimeSelector
{
	@TestVisible
	private static PrimeSelector instance = null;

	public static PrimeSelector newInstance()
	{
		if (instance == null)
		{
			instance = new PrimeSelector();
		}

		return instance;
	}

	public Prime__c getCurrentMax()
	{			
		List<Prime__c> maxPrimes = [SELECT Value__c, Index__c FROM Prime__c ORDER BY Index__c DESC LIMIT 1];
		Prime__c maxPrime = maxPrimes.size() == 1 ? maxPrimes[0] : null;
		return maxPrime;
	}
}