force/objects/Prime__c.object
<CustomObject>
    <fields>
        <fullName>Index__c</fullName>
        <label>Ordinal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Prime</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Prime Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Primes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force/main/default/classes/PrimesController.cls
public with sharing class PrimesController
{
	@AuraEnabled
	public static Object requestPrimes(Integer count)
	{
		Integer value, index;
		Prime__c currentMax = PrimeSelector.newInstance().getCurrentMax();
		if (currentMax != null) {
			value = (Integer) currentMax.Value__c;
			index = (Integer) currentMax.Index__c;
		}
		return HerokuConnector.newInstance().requestPrimes(count, value, index);
	}
}